const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('../.jac/mobui-tools/node_modules/playwright');const root=path.resolve(__dirname,'../.jac/mobui-auth-test');
(async()=>{const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({channel:process.env.STACK_BROWSER||'msedge'}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const origin='http://127.0.0.1:'+server.address().port;
 async function fresh(values={}){await page.goto(origin);await page.getByRole('button',{name:'Continue with Google',exact:true}).waitFor();await page.evaluate(v=>Object.assign(__authFixture,v),values);}
 async function google(){await page.getByRole('button',{name:'Continue with Google',exact:true}).click();}
 async function profile(){await page.getByRole('button',{name:'Open screen and scenario menu'}).click();await page.getByTestId('review-Profile').click();await page.getByText('Screen & scenario review',{exact:true}).waitFor({state:'hidden'});await page.getByText('Your sign-in',{exact:true}).waitFor();}
 try{
  await fresh();await google();await profile();assert.ok(await page.getByText('Signed in as existing-account',{exact:true}).isVisible());assert.ok(await page.getByText('Google sign-in linked',{exact:true}).isVisible());await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('button',{name:'Continue with Google',exact:true}).waitFor();
  await fresh({hold:true});await google();await page.getByRole('button',{name:'Cancel Google sign-in',exact:true}).click();await page.getByRole('button',{name:'Continue with Google',exact:true}).waitFor();await page.evaluate(()=>__authFixture.hold=false);await google();await profile();
  await fresh({admitted:false});await google();await page.getByText('Finish signing in',{exact:true}).waitFor();await page.getByLabel('Beta invitation',{exact:true}).fill('bad');await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByText('Invitation is invalid.',{exact:true}).waitFor();await page.getByLabel('Beta invitation',{exact:true}).fill('valid-fixture');await page.getByRole('button',{name:'Continue',exact:true}).click();await profile();
  await fresh({linked:false});await page.getByRole('button',{name:'Continue with Stack',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill('existing');await page.getByLabel('Password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Create account',exact:true}).click();await profile();await page.getByRole('button',{name:'Link Google sign-in',exact:true}).click();await page.getByText('Google sign-in linked',{exact:true}).waitFor();assert.ok(await page.evaluate(()=>__authFixture.linking));
  await fresh({recoverable:true});await google();await profile();await page.getByLabel('Existing Stack username',{exact:true}).fill('original-account');await page.getByLabel('Existing Stack password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Use my existing Stack account',exact:true}).click();await page.getByRole('button',{name:'Open screen and scenario menu'}).waitFor();await profile();await page.getByText('Signed in as original-account',{exact:true}).waitFor();
  await fresh({recoverable:true,admitted:false});await google();await page.getByText('Finish signing in',{exact:true}).waitFor();await page.getByLabel('Existing Stack username',{exact:true}).fill('admitted-original');await page.getByLabel('Existing Stack password',{exact:true}).fill('fixture-password');await page.getByRole('button',{name:'Use my existing Stack account',exact:true}).click();await profile();await page.getByText('Signed in as admitted-original',{exact:true}).waitFor();
  const calls=await page.evaluate(()=>__authFixture.calls);assert.ok(!calls.some(x=>x.includes('bootstrap')||x.includes('agent_google_start')));assert.deepEqual(errors,[]);
  await page.screenshot({path:path.resolve(__dirname,'../.jac/mobui-qa/oauth-profile.png')});console.log('PASS shared Jac Google sign-in, cancel/retry, invitation gate, account linking/recovery and mocked feature boundary (browser protocol fixtures, not live Google).');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1);});
