import {storage,events,services,clone} from './services';
import {resumeFingerprint} from './resume-library';
import {listingOf} from './applications-live';
export {LIBRARY_KEY,readLibrary,saveLibrary,resumeFingerprint} from './resume-library';
export const APPLICATION_STATUSES=['Ready to apply','Submitted','Assessment','Interview','Rejected'];
export const APP_KEY='stack.applications.v1';
export const PREP_KEY='stack.application.prep.v2';
export function readStore(key,fallback){try{const value=JSON.parse(storage.getItem(key));return value??fallback;}catch{return fallback;}}
export function writeStore(key,value){storage.setItem(key,JSON.stringify(value));events.emit('stack-data-changed');}
export function validEmployer(value){try{const url=new URL(value);return ['https:','http:'].includes(url.protocol)&&!!url.hostname&&!url.username&&!url.password;}catch{return false;}}
export const sampleResume={id:'sample-design',name:'Alex Morgan · Design.pdf',kind:'template',template:'jake',confirmed:true,hasLatex:true,sample:true,details:{name:'Alex Morgan',email:'alex@example.com',location:'New York, NY',experience:'Built and tested onboarding prototypes with a student product team.',education:'BA, Design · Class of 2027',skills:'Figma, prototyping, user research'}};
const specs={
 1:{responsibilities:['Prototype product experiences with designers and engineers.','Use user research to explain design decisions.'],requirements:[['Figma','Figma and prototyping experience'],['user research','Experience using user research'],['portfolio','A portfolio showing your process']],description:'Prototype product experiences with designers and engineers. Use user research to explain design decisions. Bring Figma skills and a portfolio showing your process.'},
 2:{responsibilities:['Build and test software with an engineering mentor.','Investigate API bugs and document what you learn.'],requirements:[['python','Python or equivalent programming experience'],['testing','Experience writing tests'],['sql','Basic SQL knowledge']],description:'Software internship: build Python services, investigate API bugs, write tests, and use SQL to understand data.'},
 3:{responsibilities:['Create campaign ideas for a defined audience.','Track campaign performance and share insights.'],requirements:[['writing','Clear writing and storytelling'],['analytics','Interest in marketing analytics'],['campaign','A campaign or related project']],description:'Develop brand campaigns, write clear messages, and use marketing analytics to assess results.'},
 4:{responsibilities:['Plan interviews and usability studies.','Share findings that help the team make decisions.'],requirements:[['user research','User research or interview experience'],['synthesis','Ability to synthesize research findings'],['communication','Clear communication']],description:'Plan user research, interview participants, synthesize findings, and communicate recommendations.'},
 5:{responsibilities:['Explore product design concepts.','Present your design process to the team.'],requirements:[['prototyping','Prototyping experience'],['portfolio','A portfolio of design work']],description:'Product design internship focused on prototyping and portfolio development.'}
};
export function jobFor(item){if(item.listing)return listingOf(item.listing);return {...specs[item.id]||specs[1],url:item.sourceUrl||'https://example.com/careers/'+item.id,source:'Sample employer listing',experience:'Student or recent graduate',active:item.id!==5};}
export function migrateApplication(item){return {...item,status:({Saved:'Ready to apply',Applied:'Submitted',Closed:'Rejected'})[item.status]||item.status,sourceUrl:item.sourceUrl||'https://example.com/careers/'+item.id};}
export function analysisFor(item,facts,source){const job=jobFor(item);const text=Object.values(facts||{}).filter(Boolean).join('\n');return {at:Date.now(),source,fingerprint:JSON.stringify(facts||{}),checks:job.requirements.map(([keyword,requirement])=>{const quote=text.split('\n').find(line=>line.toLowerCase().includes(keyword.toLowerCase()));return {requirement,result:quote?'Supported':'Not evidenced',listingQuote:requirement,quote:quote||'',source};}),unknowns:['Work authorization and sponsorship requirements need confirmation.','A complete portfolio and the employer’s final criteria have not been reviewed.'],summary:'Evidence from confirmed details, compared with this sample listing. This is not a hiring prediction.'};}
export function createTask(item,resume,facts,kind='application'){return {id:'application-'+item.id+'-'+Date.now(),version:2,kind,status:'queued',step:kind==='resume'?'tailor':'inspect',due:Date.now()+800,resumeFingerprint:resumeFingerprint(resume),resumeId:resume.id,resumeName:resume.name,destination:jobFor(item).url,answers:{name:facts.name||'',email:facts.email||'',authorization:''},changes:[{id:'focus',before:facts.experience||'Add a confirmed project or experience first.',after:(facts.experience||'Add a confirmed project or experience first.').replace('Built and tested','Prototyped and tested'),kept:true}],original:{...facts},approvals:{},events:[{label:'Task queued',at:Date.now()}]};}
export function tickTask(task){const next={...task,events:[...task.events]};if(task.status==='queued'){next.status='running';next.due=Date.now()+800;next.events.push({label:task.kind==='resume'?'Preparing proposed resume':'Inspecting sample form',at:Date.now()});return next;}if(task.status!=='running')return task;const order=['inspect','fit','tailor'];const pos=order.indexOf(task.step);if(pos>=0&&pos<2){next.step=order[pos+1];next.due=Date.now()+800;next.events.push({label:next.step==='fit'?'Comparing confirmed facts':'Preparing proposed resume',at:Date.now()});}else if(task.step==='tailor'){next.step='approve_resume';next.status='review';}else if(task.step==='fill'){next.step='submit';next.status='review';next.events.push({label:'Simulated form fill completed',at:Date.now()});}else if(task.step==='submit'){next.status='completed';next.receipt='SIM-'+task.id;next.events.push({label:'Simulated submission completed',at:Date.now()});}return next;}
export function approveTask(task){if(task.status!=='review')throw new Error('This task is not ready for approval.');const next={...task,approvals:{...task.approvals,[task.step]:JSON.stringify({answers:task.answers,changes:task.changes,destination:task.destination})},events:[...task.events,{label:'Approved '+task.step,at:Date.now()}]};if(task.step==='approve_resume'&&task.kind==='resume'){next.status='completed';next.receipt='SIM-TAILOR-'+task.id;next.events.push({label:'Reviewed tailored version saved',at:Date.now()});}else if(task.step==='approve_resume'){next.step='fill';next.status=task.answers.name&&task.answers.email&&task.answers.authorization?'review':'needs_input';}else if(task.step==='fill'||task.step==='submit'){next.status='running';next.due=Date.now()+1000;}return next;}
export function editTask(task,patch){return {...task,...patch,approvals:{},status:'review',step:'approve_resume'};}
export function recommendations(item){const job=jobFor(item),text=(item.role+' '+job.description).toLowerCase();const plan=[{problem_id:'role-specific',title:'Practice this role',language:'',reason:'Selected from the responsibilities in this listing.',prompt:job.responsibilities.join(' ')+' Explain how you would approach one of these tasks.',minutes:15},{problem_id:'project',title:'Tell your project story',language:'',reason:'Explain your contribution with a confirmed example.',prompt:'Describe a project, your own contribution, a tradeoff, and what you learned.',minutes:10}];if(/software|python|backend|frontend/.test(text))plan.push({problem_id:'two-sum',title:'Find a pair',language:'python',reason:'The role includes software implementation.',prompt:'Given integers and a target, return indices of two distinct values that sum to the target. Explain complexity and edge cases.',minutes:20},{problem_id:'debug-endpoint',title:'Debug a slow endpoint',language:'',reason:'The role includes API debugging.',prompt:'An endpoint slows down as saved jobs grow. Explain how you would measure, isolate, fix and verify the problem.',minutes:15});if(text.includes('sql'))plan.push({problem_id:'sql-funnel',title:'Explore a conversion funnel',language:'sql',reason:'SQL appears in the job description.',prompt:'Describe a query to measure conversion between application stages, avoiding duplicate applicants.',minutes:15});const feedback=readStore(PREP_KEY,[]).flatMap(s=>s.feedback||[]);if(feedback.some(r=>r.criterion==='reflection'&&r.score<2)&&!plan.some(r=>r.problem_id==='setback'))plan.push({problem_id:'setback',title:'Reflect on a setback',language:'',reason:'Your recent practice feedback identified reflection as a focus.',prompt:'Explain a setback, what you changed, and how you would approach it differently.',minutes:10});if(feedback.some(r=>r.criterion==='edge cases'&&r.score<2)&&!plan.some(r=>r.problem_id==='brackets'))plan.push({problem_id:'brackets',title:'Balanced brackets',language:'python',reason:'Your recent practice feedback identified edge cases as a focus.',prompt:'Check whether brackets are balanced. Explain empty input, mismatches, and complexity.',minutes:15});return plan.slice(0,7);}
export function ensurePlan(item){const all=readStore(PREP_KEY,[]);const own=recommendations(item).map(rec=>all.find(s=>s.application_id===item.id&&s.problem_id===rec.problem_id)||{...rec,session_id:'prep-'+item.id+'-'+rec.problem_id,application_id:item.id,company:item.company,role:item.role,notes:'',done:false});const retained=all.filter(s=>s.application_id===item.id&&!own.some(r=>r.session_id===s.session_id));const merged=[...own,...retained];writeStore(PREP_KEY,[...all.filter(s=>s.application_id!==item.id),...merged]);return merged;}
export const storeFile=(id,file)=>services.storeFile(id,file);
export const loadFile=id=>services.loadFile(id);

export function cancelTasks(item,label='Inputs changed; approval invalidated'){return Object.fromEntries(['task','tailorTask'].filter(k=>item[k]).map(k=>[k,{...item[k],status:'cancelled',approvals:{},events:[...(item[k].events||[]),{label,at:Date.now()}]}]));}
